# Generated by Django 3.0.3 on 2021-01-14 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20201016_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not confirmed'), (1, 'Confirmed')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='status',
            field=models.IntegerField(choices=[(1, 'Address'), (0, 'Category'), (2, 'Page')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='created_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 14, 49, 1, 217807), null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='end_time',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 14, 49, 1, 217807), null=True, verbose_name='Finish date'),
        ),
        migrations.AlterField(
            model_name='task_manegar',
            name='status',
            field=models.IntegerField(choices=[(3, 'Done!'), (1, 'In progress'), (0, 'To Do')], default=0, verbose_name='Status'),
        ),
    ]
